### ISSUE TITLE
Support one-click deployment of static files and reverse proxy api?

### ISSUE THREAD

**Issue by h7ml** [layer0-docs/layer0-docs#223]
1.  Will you recommend github Action and github App one-click deployment of static resource files built?  [vercel-action](https://github.com/marketplace/actions/vercel-action) 
2.  I will proxy the relevant api to the specified address during development, but how should I configure it after deployment. Does layer0 support proxy?

**Comment by markbrocato** [comment]
Static sites are covered here: https://docs.layer0.co/guides/static_sites
GitHub Actions are covered here: https://docs.layer0.co/guides/v4.8.2/deploy_apps#section_github_actions
Proxying an origin server is covered here: https://docs.layer0.co/guides/cookbook#section_proxying_a_backend
