### ISSUE TITLE
Version change doesn't work accurately

### ISSUE THREAD

**Issue by rishi-raj-jain** [layer0-docs/layer0-docs#68]
Steps to reproduce:

Scenario 1:
- Go to [docs.layer0.co](https://docs.layer0.co),
- Select the oldest version available,
- No change happens (whether change in frameworks/design/sidebar)

Scenario 2:
- Go to https://docs.layer0.co/guides/next,
- Select the oldest version available,
- Click on the top left corner logo to navigate to the docs.layer0.co,
- Find that the docs version switches to the latest available (instead of the one selected before)

**Comment by RaeesBhatti** [comment]
It doesn't seem like an issue anymore.
